FROM ubuntu:xenial
MAINTAINER Zach Musgrave <ztm@zachm.us>

## This Dockerfile is *almost* the same as our production build,
## but it installs the dev requirements and runs all the tests.

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y libyaml-dev libpcre3-dev
RUN pip3 install --upgrade pip

ADD requirements-dev.txt /code/requirements-dev.txt
ADD requirements.txt /code/requirements.txt
RUN pip3 install -Ur /code/requirements-dev.txt

ADD . /code
WORKDIR /code

CMD tox && tox -e coverage
